print("Обработка на изключения")
# Контролируем код:
try:
    num = int(input("Въведете цяло число: "))
    print("Вие въведохте числото " + str(num))
# Обработка на изключение:
except:
    print("Трябваше да въведете цяло число!")
print("Благодаря за съдействието!")
